export default [
  {
    description: "Energia elétrica",
    amount: "150.55",
    type: "saída",
    frequency: "recorrente",
    date: "2020-01-10",
  },
  {
    description: "Água",
    amount: "75.55",
    type: "saída",
    frequency: "recorrente",
    date: "2020-01-15",
  },
  {
    description: "Telefone",
    amount: "99.99",
    type: "saída",
    frequency: "recorrente",
    date: "2020-01-23",
  },
  {
    description: "Plano de Saúde",
    amount: "300.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-01-23",
  },
  {
    description: "Compras do mês",
    amount: "625.78",
    type: "saída",
    frequency: "recorrente",
    date: "2020-01-23",
  },
  {
    description: "Lanche",
    amount: "45.70",
    type: "saída",
    frequency: "eventual",
    date: "2020-01-23",
  },
  {
    description: "Blusa",
    amount: "95.70",
    type: "saída",
    frequency: "eventual",
    date: "2020-01-23",
  },
  {
    description: "Energia elétrica",
    amount: "125.55",
    type: "saída",
    frequency: "recorrente",
    date: "2020-02-10",
  },
  {
    description: "Água",
    amount: "90.15",
    type: "saída",
    frequency: "recorrente",
    date: "2020-02-15",
  },
  {
    description: "Telefone",
    amount: "99.99",
    type: "saída",
    frequency: "recorrente",
    date: "2020-02-23",
  },
  {
    description: "Plano de Saúde",
    amount: "300.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-02-23",
  },
  {
    description: "Compras do mês",
    amount: "540.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-02-25",
  },
  {
    description: "Parcela do Celular 1/5",
    amount: "150.99",
    type: "saída",
    frequency: "eventual",
    date: "2020-02-26",
  },
  {
    description: "Cinema",
    amount: "45.00",
    type: "saída",
    frequency: "eventual",
    date: "2020-02-23",
  },
  {
    description: "Energia elétrica",
    amount: "97.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-03-10",
  },
  {
    description: "Água",
    amount: "100.10",
    type: "saída",
    frequency: "recorrente",
    date: "2020-03-15",
  },
  {
    description: "Telefone",
    amount: "99.99",
    type: "saída",
    frequency: "recorrente",
    date: "2020-03-23",
  },
  {
    description: "Plano de Saúde",
    amount: "300.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-03-23",
  },
  {
    description: "Compras do mês",
    amount: "800.50",
    type: "saída",
    frequency: "recorrente",
    date: "2020-03-17",
  },
  {
    description: "Parcela do Celular 2/5",
    amount: "150.99",
    type: "saída",
    frequency: "eventual",
    date: "2020-03-18",
  },
  {
    description: "Troca de Oléo do carro",
    amount: "90.00",
    type: "saída",
    frequency: "eventual",
    date: "2020-03-23",
  },
  {
    description: "Energia elétrica",
    amount: "75.99",
    type: "saída",
    frequency: "recorrente",
    date: "2020-04-10",
  },
  {
    description: "Água",
    amount: "80.33",
    type: "saída",
    frequency: "recorrente",
    date: "2020-04-15",
  },
  {
    description: "Telefone",
    amount: "99.99",
    type: "saída",
    frequency: "recorrente",
    date: "2020-04-23",
  },
  {
    description: "Plano de Saúde",
    amount: "300.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-04-23",
  },
  {
    description: "Compras do mês",
    amount: "600.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-04-25",
  },
  {
    description: "Parcela do Celular 3/5",
    amount: "150.99",
    type: "saída",
    frequency: "eventual",
    date: "2020-04-26",
  },
  {
    description: "Ebook de React Js",
    amount: "85.95",
    type: "saída",
    frequency: "eventual",
    date: "2020-04-13",
  },
  {
    description: "Energia elétrica",
    amount: "125.55",
    type: "saída",
    frequency: "recorrente",
    date: "2020-05-10",
  },
  {
    description: "Água",
    amount: "90.15",
    type: "saída",
    frequency: "recorrente",
    date: "2020-05-15",
  },
  {
    description: "Telefone",
    amount: "99.99",
    type: "saída",
    frequency: "recorrente",
    date: "2020-05-23",
  },
  {
    description: "Plano de Saúde",
    amount: "300.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-05-23",
  },
  {
    description: "Compras do mês",
    amount: "540.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-05-25",
  },
  {
    description: "Parcela do Celular 4/5",
    amount: "150.99",
    type: "saída",
    frequency: "eventual",
    date: "2020-05-26",
  },
  {
    description: "Blusa Iron Man",
    amount: "150.00",
    type: "saída",
    frequency: "eventual",
    date: "2020-01-23",
  },
  {
    description: "Energia elétrica",
    amount: "200.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-06-10",
  },
  {
    description: "Água",
    amount: "150.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-06-15",
  },
  {
    description: "Telefone",
    amount: "99.99",
    type: "saída",
    frequency: "recorrente",
    date: "2020-06-23",
  },
  {
    description: "Plano de Saúde",
    amount: "300.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-06-23",
  },
  {
    description: "Compras do mês",
    amount: "559.15",
    type: "saída",
    frequency: "recorrente",
    date: "2020-06-25",
  },
  {
    description: "Parcela do Celular 5/5",
    amount: "150.99",
    type: "saída",
    frequency: "eventual",
    date: "2020-06-26",
  },
  {
    description: "Perfume",
    amount: "250.00",
    type: "saída",
    frequency: "eventual",
    date: "2020-06-21",
  },
  {
    description: "Energia elétrica",
    amount: "250.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-07-10",
  },
  {
    description: "Água",
    amount: "90.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-07-15",
  },
  {
    description: "Telefone",
    amount: "99.99",
    type: "saída",
    frequency: "recorrente",
    date: "2020-07-23",
  },
  {
    description: "Plano de Saúde",
    amount: "300.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-07-23",
  },
  {
    description: "Compras do mês",
    amount: "700.00",
    type: "saída",
    frequency: "recorrente",
    date: "2022-07-25",
  },
  {
    description: "Cafeteira",
    amount: "250.00",
    type: "saída",
    frequency: "eventual",
    date: "2020-07-26",
  },
  {
    description: "Pizza",
    amount: "60.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-07-19",
  },
  {
    description: "Energia elétrica",
    amount: "150.55",
    type: "saída",
    frequency: "recorrente",
    date: "2020-01-10",
  },
  {
    description: "Água",
    amount: "75.55",
    type: "saída",
    frequency: "recorrente",
    date: "2020-01-15",
  },
  {
    description: "Telefone",
    amount: "99.99",
    type: "saída",
    frequency: "recorrente",
    date: "2020-01-23",
  },
  {
    description: "Plano de Saúde",
    amount: "300.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-01-23",
  },
  {
    description: "Compras do mês",
    amount: "625.78",
    type: "saída",
    frequency: "recorrente",
    date: "2020-01-23",
  },
  {
    description: "Lanche",
    amount: "45.70",
    type: "saída",
    frequency: "eventual",
    date: "2020-01-23",
  },
  {
    description: "Blusa",
    amount: "95.70",
    type: "saída",
    frequency: "eventual",
    date: "2020-01-23",
  },
  {
    description: "Energia elétrica",
    amount: "125.55",
    type: "saída",
    frequency: "recorrente",
    date: "2020-02-10",
  },
  {
    description: "Água",
    amount: "90.15",
    type: "saída",
    frequency: "recorrente",
    date: "2020-02-15",
  },
  {
    description: "Telefone",
    amount: "99.99",
    type: "saída",
    frequency: "recorrente",
    date: "2020-02-23",
  },
  {
    description: "Plano de Saúde",
    amount: "300.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-02-23",
  },
  {
    description: "Compras do mês",
    amount: "540.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-02-25",
  },
  {
    description: "Parcela do Celular 1/5",
    amount: "150.99",
    type: "saída",
    frequency: "eventual",
    date: "2020-02-26",
  },
  {
    description: "Cinema",
    amount: "45.00",
    type: "saída",
    frequency: "eventual",
    date: "2020-02-23",
  },
  {
    description: "Energia elétrica",
    amount: "97.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-03-10",
  },
  {
    description: "Água",
    amount: "100.10",
    type: "saída",
    frequency: "recorrente",
    date: "2020-03-15",
  },
  {
    description: "Telefone",
    amount: "99.99",
    type: "saída",
    frequency: "recorrente",
    date: "2020-03-23",
  },
  {
    description: "Plano de Saúde",
    amount: "300.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-03-23",
  },
  {
    description: "Compras do mês",
    amount: "800.50",
    type: "saída",
    frequency: "recorrente",
    date: "2020-03-17",
  },
  {
    description: "Parcela do Celular 2/5",
    amount: "150.99",
    type: "saída",
    frequency: "eventual",
    date: "2020-03-18",
  },
  {
    description: "Troca de Oléo do carro",
    amount: "90.00",
    type: "saída",
    frequency: "eventual",
    date: "2020-03-23",
  },
  {
    description: "Energia elétrica",
    amount: "75.99",
    type: "saída",
    frequency: "recorrente",
    date: "2020-04-10",
  },
  {
    description: "Água",
    amount: "80.33",
    type: "saída",
    frequency: "recorrente",
    date: "2020-04-15",
  },
  {
    description: "Telefone",
    amount: "99.99",
    type: "saída",
    frequency: "recorrente",
    date: "2020-04-23",
  },
  {
    description: "Plano de Saúde",
    amount: "300.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-04-23",
  },
  {
    description: "Compras do mês",
    amount: "600.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-04-25",
  },
  {
    description: "Parcela do Celular 3/5",
    amount: "150.99",
    type: "saída",
    frequency: "eventual",
    date: "2020-04-26",
  },
  {
    description: "Ebook de React Js",
    amount: "85.95",
    type: "saída",
    frequency: "eventual",
    date: "2020-04-13",
  },
  {
    description: "Energia elétrica",
    amount: "125.55",
    type: "saída",
    frequency: "recorrente",
    date: "2020-05-10",
  },
  {
    description: "Água",
    amount: "90.15",
    type: "saída",
    frequency: "recorrente",
    date: "2020-05-15",
  },
  {
    description: "Telefone",
    amount: "99.99",
    type: "saída",
    frequency: "recorrente",
    date: "2020-05-23",
  },
  {
    description: "Plano de Saúde",
    amount: "300.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-05-23",
  },
  {
    description: "Compras do mês",
    amount: "540.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-05-25",
  },
  {
    description: "Parcela do Celular 4/5",
    amount: "150.99",
    type: "saída",
    frequency: "eventual",
    date: "2020-05-26",
  },
  {
    description: "Blusa Iron Man",
    amount: "150.00",
    type: "saída",
    frequency: "eventual",
    date: "2020-01-23",
  },
  {
    description: "Energia elétrica",
    amount: "200.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-06-10",
  },
  {
    description: "Água",
    amount: "150.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-06-15",
  },
  {
    description: "Telefone",
    amount: "99.99",
    type: "saída",
    frequency: "recorrente",
    date: "2020-06-23",
  },
  {
    description: "Plano de Saúde",
    amount: "300.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-06-23",
  },
  {
    description: "Compras do mês",
    amount: "559.15",
    type: "saída",
    frequency: "recorrente",
    date: "2020-06-25",
  },
  {
    description: "Parcela do Celular 5/5",
    amount: "150.99",
    type: "saída",
    frequency: "eventual",
    date: "2020-06-26",
  },
  {
    description: "Perfume",
    amount: "250.00",
    type: "saída",
    frequency: "eventual",
    date: "2020-06-21",
  },
  {
    description: "Energia elétrica",
    amount: "250.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-07-10",
  },
  {
    description: "Água",
    amount: "90.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-07-15",
  },
  {
    description: "Telefone",
    amount: "99.99",
    type: "saída",
    frequency: "recorrente",
    date: "2020-07-23",
  },
  {
    description: "Plano de Saúde",
    amount: "300.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-07-23",
  },
  {
    description: "Compras do mês",
    amount: "700.00",
    type: "saída",
    frequency: "recorrente",
    date: "2022-07-25",
  },
  {
    description: "Cafeteira",
    amount: "250.00",
    type: "saída",
    frequency: "eventual",
    date: "2020-07-26",
  },
  {
    description: "Pizza",
    amount: "60.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-07-19",
  },
  {
    description: "Água",
    amount: "80.30",
    type: "saída",
    frequency: "recorrente",
    date: "2020-03-10",
  },
  {
    description: "Telefone",
    amount: "90.10",
    type: "saída",
    frequency: "recorrente",
    date: "2020-03-15",
  },
  {
    description: "Internet",
    amount: "120.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-03-20",
  },
  {
    description: "Aluguel",
    amount: "750.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-03-25",
  },
  {
    description: "Supermercado",
    amount: "450.20",
    type: "saída",
    frequency: "recorrente",
    date: "2020-04-05",
  },
  {
    description: "Plano de Saúde",
    amount: "320.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-04-10",
  },
  {
    description: "Academia",
    amount: "99.99",
    type: "saída",
    frequency: "recorrente",
    date: "2020-04-15",
  },
  {
    description: "Energia elétrica",
    amount: "130.75",
    type: "saída",
    frequency: "recorrente",
    date: "2020-04-20",
  },
  {
    description: "Água",
    amount: "70.25",
    type: "saída",
    frequency: "recorrente",
    date: "2020-04-25",
  },
  {
    description: "Telefone",
    amount: "85.50",
    type: "saída",
    frequency: "recorrente",
    date: "2020-05-05",
  },
  {
    description: "Internet",
    amount: "110.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-05-10",
  },
  {
    description: "Aluguel",
    amount: "740.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-05-15",
  },
  {
    description: "Supermercado",
    amount: "460.45",
    type: "saída",
    frequency: "recorrente",
    date: "2020-05-20",
  },
  {
    description: "Plano de Saúde",
    amount: "310.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-05-25",
  },
  {
    description: "Academia",
    amount: "89.99",
    type: "saída",
    frequency: "recorrente",
    date: "2020-06-05",
  },
  {
    description: "Energia elétrica",
    amount: "140.50",
    type: "saída",
    frequency: "recorrente",
    date: "2020-06-10",
  },
  {
    description: "Água",
    amount: "75.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-06-15",
  },
  {
    description: "Telefone",
    amount: "88.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-06-20",
  },
  {
    description: "Internet",
    amount: "115.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-06-25",
  },
  {
    description: "Aluguel",
    amount: "730.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-07-05",
  },
  {
    description: "Supermercado",
    amount: "470.60",
    type: "saída",
    frequency: "recorrente",
    date: "2020-07-10",
  },
  {
    description: "Plano de Saúde",
    amount: "300.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-07-15",
  },
  {
    description: "Academia",
    amount: "79.99",
    type: "saída",
    frequency: "recorrente",
    date: "2020-07-20",
  },
  {
    description: "Energia elétrica",
    amount: "135.75",
    type: "saída",
    frequency: "recorrente",
    date: "2020-07-25",
  },
  {
    description: "Água",
    amount: "80.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-08-05",
  },
  {
    description: "Telefone",
    amount: "95.50",
    type: "saída",
    frequency: "recorrente",
    date: "2020-08-10",
  },
  {
    description: "Internet",
    amount: "125.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-08-15",
  },
  {
    description: "Aluguel",
    amount: "720.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-08-20",
  },
  {
    description: "Supermercado",
    amount: "480.75",
    type: "saída",
    frequency: "recorrente",
    date: "2020-08-25",
  },
  {
    description: "Plano de Saúde",
    amount: "290.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-09-05",
  },
  {
    description: "Academia",
    amount: "69.99",
    type: "saída",
    frequency: "recorrente",
    date: "2020-09-10",
  },
  {
    description: "Energia elétrica",
    amount: "145.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-09-15",
  },
  {
    description: "Água",
    amount: "85.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-09-20",
  },
  {
    description: "Telefone",
    amount: "100.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-09-25",
  },
  {
    description: "Internet",
    amount: "130.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-10-05",
  },
  {
    description: "Aluguel",
    amount: "710.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-10-10",
  },
  {
    description: "Supermercado",
    amount: "490.90",
    type: "saída",
    frequency: "recorrente",
    date: "2020-10-15",
  },
  {
    description: "Plano de Saúde",
    amount: "280.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-10-20",
  },
  {
    description: "Academia",
    amount: "59.99",
    type: "saída",
    frequency: "recorrente",
    date: "2020-10-25",
  },
  {
    description: "Energia elétrica",
    amount: "150.25",
    type: "saída",
    frequency: "recorrente",
    date: "2020-11-05",
  },
  {
    description: "Água",
    amount: "90.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-11-10",
  },
  {
    description: "Telefone",
    amount: "105.50",
    type: "saída",
    frequency: "recorrente",
    date: "2020-11-15",
  },
  {
    description: "Internet",
    amount: "135.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-11-20",
  },
  {
    description: "Aluguel",
    amount: "700.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-11-25",
  },
  {
    description: "Supermercado",
    amount: "500.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-12-05",
  },
  {
    description: "Viagem",
    amount: "1200.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-03-22",
  },
  {
    description: "Conserto do carro",
    amount: "450.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-04-11",
  },
  {
    description: "Presente de aniversário",
    amount: "200.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-05-05",
  },
  {
    description: "Reforma da casa",
    amount: "3000.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-06-15",
  },
  {
    description: "Compra de móveis",
    amount: "1500.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-07-22",
  },
  {
    description: "Show",
    amount: "350.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-08-10",
  },
  {
    description: "Curso online",
    amount: "100.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-09-07",
  },
  {
    description: "Consulta médica",
    amount: "250.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-10-01",
  },
  {
    description: "Jantar especial",
    amount: "180.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-11-17",
  },
  {
    description: "Cinema",
    amount: "50.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-12-19",
  },
  {
    description: "Roupa nova",
    amount: "300.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-02-15",
  },
  {
    description: "Material de construção",
    amount: "750.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-01-25",
  },
  {
    description: "Parque de diversões",
    amount: "120.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-03-13",
  },
  {
    description: "Taxa de matrícula",
    amount: "500.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-04-29",
  },
  {
    description: "Remédios",
    amount: "90.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-05-16",
  },
  {
    description: "Pet shop",
    amount: "75.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-06-03",
  },
  {
    description: "Eletrônicos",
    amount: "800.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-07-30",
  },
  {
    description: "Viagem de férias",
    amount: "2500.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-08-14",
  },
  {
    description: "Conserto de eletrodoméstico",
    amount: "350.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-09-08",
  },
  {
    description: "Evento social",
    amount: "100.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-10-23",
  },
  {
    description: "Livros",
    amount: "60.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-11-12",
  },
  {
    description: "Doação",
    amount: "200.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-12-06",
  },
  {
    description: "Cafeteria",
    amount: "40.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-01-18",
  },
  {
    description: "Almoço com amigos",
    amount: "150.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-02-28",
  },
  {
    description: "Workshop",
    amount: "80.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-03-10",
  },
  {
    description: "Jogo de futebol",
    amount: "70.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-04-07",
  },
  {
    description: "Show musical",
    amount: "300.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-05-19",
  },
  {
    description: "Teatro",
    amount: "120.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-06-11",
  },
  {
    description: "Curso presencial",
    amount: "150.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-07-26",
  },
  {
    description: "Estacionamento",
    amount: "20.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-08-31",
  },
  {
    description: "Barbearia",
    amount: "50.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-09-20",
  },
  {
    description: "Aluguel de carro",
    amount: "200.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-10-15",
  },
  {
    description: "Compras de Natal",
    amount: "600.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-11-24",
  },
  {
    description: "Conserto de bicicleta",
    amount: "80.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-12-05",
  },
  {
    description: "Massagem",
    amount: "120.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-01-21",
  },
  {
    description: "Lavagem de carro",
    amount: "30.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-02-04",
  },
  {
    description: "Jantar romântico",
    amount: "250.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-03-16",
  },
  {
    description: "Bebidas",
    amount: "100.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-04-09",
  },
  {
    description: "Curso de culinária",
    amount: "200.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-05-03",
  },
  {
    description: "Compra de acessórios",
    amount: "150.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-06-14",
  },
  {
    description: "Viagem de fim de semana",
    amount: "500.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-07-20",
  },
  {
    description: "Almoço em família",
    amount: "120.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-08-18",
  },
  {
    description: "Passeio no parque",
    amount: "30.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-09-06",
  },
  {
    description: "Ingresso de cinema",
    amount: "45.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-10-22",
  },
  {
    description: "Jogo de tabuleiro",
    amount: "60.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-11-30",
  },
  {
    description: "Viagem",
    amount: "1200.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-03-22",
  },
  {
    description: "Conserto do carro",
    amount: "450.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-04-11",
  },
  {
    description: "Presente de aniversário",
    amount: "200.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-05-05",
  },
  {
    description: "Reforma da casa",
    amount: "3000.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-06-15",
  },
  {
    description: "Compra de móveis",
    amount: "1500.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-07-22",
  },
  {
    description: "Show",
    amount: "350.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-08-10",
  },
  {
    description: "Curso online",
    amount: "100.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-09-07",
  },
  {
    description: "Consulta médica",
    amount: "250.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-10-01",
  },
  {
    description: "Jantar especial",
    amount: "180.00",
    type: "saída",
    frequency: "eventual",
    date: "2022-11-17",
  },
  {
    description: "Cinema",
    amount: "50.00",
    type: "saída",
    frequency: "eventual",
    date: "2022-12-19",
  },
  {
    description: "Roupa nova",
    amount: "300.00",
    type: "saída",
    frequency: "eventual",
    date: "2022-02-15",
  },
  {
    description: "Material de construção",
    amount: "750.00",
    type: "saída",
    frequency: "eventual",
    date: "2022-01-25",
  },
  {
    description: "Parque de diversões",
    amount: "120.00",
    type: "saída",
    frequency: "eventual",
    date: "2022-03-13",
  },
  {
    description: "Taxa de matrícula",
    amount: "500.00",
    type: "saída",
    frequency: "eventual",
    date: "2022-04-29",
  },
  {
    description: "Remédios",
    amount: "90.00",
    type: "saída",
    frequency: "eventual",
    date: "2022-05-16",
  },
  {
    description: "Pet shop",
    amount: "75.00",
    type: "saída",
    frequency: "eventual",
    date: "2022-06-03",
  },
  {
    description: "Eletrônicos",
    amount: "800.00",
    type: "saída",
    frequency: "eventual",
    date: "2022-07-30",
  },
  {
    description: "Viagem de férias",
    amount: "2500.00",
    type: "saída",
    frequency: "eventual",
    date: "2022-08-14",
  },
  {
    description: "Conserto de eletrodoméstico",
    amount: "350.00",
    type: "saída",
    frequency: "eventual",
    date: "2022-09-08",
  },
  {
    description: "Evento social",
    amount: "100.00",
    type: "saída",
    frequency: "eventual",
    date: "2022-10-23",
  },
  {
    description: "Livros",
    amount: "60.00",
    type: "saída",
    frequency: "eventual",
    date: "2023-11-12",
  },
  {
    description: "Doação",
    amount: "200.00",
    type: "saída",
    frequency: "eventual",
    date: "2023-12-06",
  },
  {
    description: "Cafeteria",
    amount: "40.00",
    type: "saída",
    frequency: "eventual",
    date: "2023-01-18",
  },
  {
    description: "Almoço com amigos",
    amount: "150.00",
    type: "saída",
    frequency: "eventual",
    date: "2023-02-28",
  },
  {
    description: "Workshop",
    amount: "80.00",
    type: "saída",
    frequency: "eventual",
    date: "2023-03-10",
  },
  {
    description: "Jogo de futebol",
    amount: "70.00",
    type: "saída",
    frequency: "eventual",
    date: "2023-04-07",
  },
  {
    description: "Show musical",
    amount: "300.00",
    type: "saída",
    frequency: "eventual",
    date: "2023-05-19",
  },
  {
    description: "Teatro",
    amount: "120.00",
    type: "saída",
    frequency: "eventual",
    date: "2023-06-11",
  },
  {
    description: "Curso presencial",
    amount: "150.00",
    type: "saída",
    frequency: "eventual",
    date: "2023-07-26",
  },
  {
    description: "Estacionamento",
    amount: "20.00",
    type: "saída",
    frequency: "eventual",
    date: "2024-08-31",
  },
  {
    description: "Barbearia",
    amount: "50.00",
    type: "saída",
    frequency: "eventual",
    date: "2024-09-20",
  },
  {
    description: "Aluguel de carro",
    amount: "200.00",
    type: "saída",
    frequency: "eventual",
    date: "2024-10-15",
  },
  {
    description: "Compras de Natal",
    amount: "600.00",
    type: "saída",
    frequency: "eventual",
    date: "2024-11-24",
  },
  {
    description: "Conserto de bicicleta",
    amount: "80.00",
    type: "saída",
    frequency: "eventual",
    date: "2024-12-05",
  },
  {
    description: "Massagem",
    amount: "120.00",
    type: "saída",
    frequency: "eventual",
    date: "2024-07-21",
  },
  {
    description: "Lavagem de carro",
    amount: "30.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-06-04",
  },
  {
    description: "Jantar romântico",
    amount: "250.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-05-16",
  },
  {
    description: "Bebidas",
    amount: "100.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-04-09",
  },
  {
    description: "Curso de culinária",
    amount: "200.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-03-03",
  },
  {
    description: "Compra de acessórios",
    amount: "150.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-02-14",
  },
  {
    description: "Viagem de fim de semana",
    amount: "500.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-01-20",
  },
  {
    description: "Almoço em família",
    amount: "120.00",
    type: "saída",
    frequency: "eventual",
    date: "2021-08-18",
  },
  {
    description: "Passeio no parque",
    amount: "30.00",
    type: "saída",
    frequency: "eventual",
    date: "2024-09-06",
  },
  {
    description: "Ingresso de cinema",
    amount: "45.00",
    type: "saída",
    frequency: "eventual",
    date: "2023-10-22",
  },
  {
    description: "Jogo de tabuleiro",
    amount: "60.00",
    type: "saída",
    frequency: "eventual",
    date: "2022-11-30",
  },
];
