export default [
  {
    description: "Salário",
    amount: "1300.52",
    type: "entrada",
    frequency: "recorrente",
    date: "2020-01-10",
  },
  {
    description: "Freela",
    amount: "150.13",
    type: "entrada",
    frequency: "eventual",
    date: "2020-01-17",
  },
  {
    description: "Salário",
    amount: "2500.23",
    type: "entrada",
    frequency: "recorrente",
    date: "2020-02-10",
  },
  {
    description: "Freela site",
    amount: "900.23",
    type: "entrada",
    frequency: "eventual",
    date: "2020-02-21",
  },
  {
    description: "Freela app",
    amount: "950.92",
    type: "entrada",
    frequency: "eventual",
    date: "2020-02-23",
  },
  {
    description: "Salário",
    amount: "2500.25",
    type: "entrada",
    frequency: "recorrente",
    date: "2024-01-10",
  },
  {
    description: "Salário",
    amount: "2500.18",
    type: "entrada",
    frequency: "recorrente",
    date: "2024-04-10",
  },
  {
    description: "Salário",
    amount: "2500.15",
    type: "entrada",
    frequency: "recorrente",
    date: "2024-05-10",
  },
  {
    description: "Salário",
    amount: "1500.12",
    type: "entrada",
    frequency: "recorrente",
    date: "2024-06-10",
  },
  {
    description: "Salário",
    amount: "2500.00",
    type: "entrada",
    frequency: "recorrente",
    date: "2020-07-10",
  },
  {
    description: "Salário",
    amount: "2500.00",
    type: "entrada",
    frequency: "recorrente",
    date: "2020-08-10",
  },
  {
    description: "Salário",
    amount: "2500.00",
    type: "entrada",
    frequency: "recorrente",
    date: "2020-09-10",
  },
  {
    description: "Salário",
    amount: "2500.00",
    type: "entrada",
    frequency: "recorrente",
    date: "2020-10-10",
  },
  {
    description: "Salário",
    amount: "2500.00",
    type: "entrada",
    frequency: "recorrente",
    date: "2020-11-10",
  },
  {
    description: "Salário",
    amount: "2500.00",
    type: "entrada",
    frequency: "recorrente",
    date: "2020-12-10",
  },
  {
    description: "Salário",
    amount: "2500.00",
    type: "entrada",
    frequency: "recorrente",
    date: "2021-01-10",
  },
  {
    description: "Salário",
    amount: "2500.00",
    type: "entrada",
    frequency: "recorrente",
    date: "2021-02-10",
  },
  {
    description: "Salário",
    amount: "2500.00",
    type: "entrada",
    frequency: "recorrente",
    date: "2021-03-10",
  },
  {
    description: "Freela de design",
    amount: "450.00",
    type: "entrada",
    frequency: "eventual",
    date: "2021-03-15",
  },
  {
    description: "Venda de equipamentos",
    amount: "1200.00",
    type: "entrada",
    frequency: "eventual",
    date: "2021-03-20",
  },
  {
    description: "Salário",
    amount: "2500.00",
    type: "entrada",
    frequency: "recorrente",
    date: "2021-04-10",
  },
  {
    description: "Freela de desenvolvimento",
    amount: "950.00",
    type: "entrada",
    frequency: "eventual",
    date: "2021-04-15",
  },
  {
    description: "Reembolso",
    amount: "150.00",
    type: "entrada",
    frequency: "eventual",
    date: "2021-04-25",
  },
  {
    description: "Salário",
    amount: "2500.00",
    type: "entrada",
    frequency: "recorrente",
    date: "2021-05-10",
  },
  {
    description: "Freela de marketing",
    amount: "700.00",
    type: "entrada",
    frequency: "eventual",
    date: "2021-05-18",
  },
  {
    description: "Dividendo de ações",
    amount: "350.00",
    type: "entrada",
    frequency: "eventual",
    date: "2021-05-25",
  },
  {
    description: "Salário",
    amount: "2500.00",
    type: "entrada",
    frequency: "recorrente",
    date: "2021-06-10",
  },
  {
    description: "Venda de projetos",
    amount: "600.00",
    type: "entrada",
    frequency: "eventual",
    date: "2021-06-15",
  },
  {
    description: "Salário",
    amount: "2500.00",
    type: "entrada",
    frequency: "recorrente",
    date: "2021-07-10",
  },
  {
    description: "Bônus",
    amount: "500.00",
    type: "entrada",
    frequency: "eventual",
    date: "2021-07-20",
  },
  {
    description: "Freela de tradução",
    amount: "300.00",
    type: "entrada",
    frequency: "eventual",
    date: "2021-07-25",
  },
  {
    description: "Salário",
    amount: "2500.00",
    type: "entrada",
    frequency: "recorrente",
    date: "2021-08-10",
  },
  {
    description: "Consultoria",
    amount: "750.00",
    type: "entrada",
    frequency: "eventual",
    date: "2021-08-15",
  },
  {
    description: "Renda de aluguel",
    amount: "1200.00",
    type: "entrada",
    frequency: "recorrente",
    date: "2021-08-20",
  },
  {
    description: "Salário",
    amount: "2500.00",
    type: "entrada",
    frequency: "recorrente",
    date: "2021-09-10",
  },
  {
    description: "Freela de edição de vídeo",
    amount: "800.00",
    type: "entrada",
    frequency: "eventual",
    date: "2021-09-15",
  },
  {
    description: "Reembolso de despesas",
    amount: "150.00",
    type: "entrada",
    frequency: "eventual",
    date: "2021-09-25",
  },
  {
    description: "Salário",
    amount: "2500.00",
    type: "entrada",
    frequency: "recorrente",
    date: "2021-10-10",
  },
  {
    description: "Freela de fotografia",
    amount: "500.00",
    type: "entrada",
    frequency: "eventual",
    date: "2021-10-15",
  },
  {
    description: "Dividendo de fundos",
    amount: "300.00",
    type: "entrada",
    frequency: "eventual",
    date: "2021-10-25",
  },
  {
    description: "Salário",
    amount: "2500.00",
    type: "entrada",
    frequency: "recorrente",
    date: "2021-11-10",
  },
  {
    description: "Freela de design gráfico",
    amount: "700.00",
    type: "entrada",
    frequency: "eventual",
    date: "2021-11-20",
  },
  {
    description: "Consultoria financeira",
    amount: "450.00",
    type: "entrada",
    frequency: "eventual",
    date: "2021-11-30",
  },
  {
    description: "Salário",
    amount: "2500.00",
    type: "entrada",
    frequency: "recorrente",
    date: "2021-12-10",
  },
  {
    description: "Freela de redação",
    amount: "350.00",
    type: "entrada",
    frequency: "eventual",
    date: "2021-12-15",
  },
  {
    description: "Venda de produtos",
    amount: "1500.00",
    type: "entrada",
    frequency: "eventual",
    date: "2021-12-20",
  },
  {
    description: "Salário",
    amount: "2500.00",
    type: "entrada",
    frequency: "recorrente",
    date: "2022-01-10",
  },
  {
    description: "Freela de consultoria",
    amount: "800.00",
    type: "entrada",
    frequency: "eventual",
    date: "2022-01-15",
  },
  {
    description: "Bônus anual",
    amount: "3000.00",
    type: "entrada",
    frequency: "eventual",
    date: "2022-01-20",
  },
  {
    description: "Salário",
    amount: "2500.00",
    type: "entrada",
    frequency: "recorrente",
    date: "2022-02-10",
  },
  {
    description: "Freela de desenvolvimento",
    amount: "1000.00",
    type: "entrada",
    frequency: "eventual",
    date: "2022-02-15",
  },
  {
    description: "Reembolso de viagem",
    amount: "400.00",
    type: "entrada",
    frequency: "eventual",
    date: "2022-02-20",
  },
  {
    description: "Salário",
    amount: "2500.00",
    type: "entrada",
    frequency: "recorrente",
    date: "2022-03-10",
  },
  {
    description: "Freela de análise de dados",
    amount: "900.00",
    type: "entrada",
    frequency: "eventual",
    date: "2022-03-15",
  },
  {
    description: "Consultoria de TI",
    amount: "600.00",
    type: "entrada",
    frequency: "eventual",
    date: "2022-03-20",
  },
  {
    description: "Salário",
    amount: "2500.00",
    type: "entrada",
    frequency: "recorrente",
    date: "2022-04-10",
  },
  {
    description: "Freela de produção de conteúdo",
    amount: "400.00",
    type: "entrada",
    frequency: "eventual",
    date: "2022-04-15",
  },
  {
    description: "Dividendo de investimentos",
    amount: "350.00",
    type: "entrada",
    frequency: "eventual",
    date: "2022-04-20",
  },
  {
    description: "Salário",
    amount: "2500.00",
    type: "entrada",
    frequency: "recorrente",
    date: "2022-05-10",
  },
  {
    description: "Freela de design UI/UX",
    amount: "800.00",
    type: "entrada",
    frequency: "eventual",
    date: "2022-05-15",
  },
  {
    description: "Venda de artesanato",
    amount: "500.00",
    type: "entrada",
    frequency: "eventual",
    date: "2022-05-20",
  },
];
